---
- name: Add repository
  ansible.builtin.import_tasks: repository.yml
  tags: repository
- name: Install packages
  ansible.builtin.import_tasks: package.yml
  tags: package
- name: Create/update setting
  ansible.builtin.import_tasks: setting.yml
  tags: setting
- name: Setup service
  ansible.builtin.import_tasks: service.yml
  tags: service
