---
- name: Install php packages
  ansible.builtin.apt:
    name: "{{ php_packages }}"
- name: Install composer
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/{{ php_composer_version }}/composer.phar
    dest: /usr/local/bin/composer
    mode: "0755"
- name: Execute update alternatives(php)
  community.general.alternatives:
    name: "{{ item }}"
    path: /usr/bin/{{ item }}{{ php_version }}
  loop:
    - php
    - phar
    - phar.phar
- name: Execute update alternatives(php-dev)
  when: "'php' + (php_version | string) + '-dev' in php_packages"
  block:
    - name: execute update alternatives(php-dev)
      community.general.alternatives:
        name: "{{ item }}"
        path: /usr/bin/{{ item }}{{ php_version }}
      loop:
        - phpize
        - php-config
- name: Execute update alternatives(php-fpm)
  when: "'php' + (php_version | string) + '-fpm' in php_packages"
  block:
    - name: execute update alternatives(php-fpm)
      community.general.alternatives:
        name: php-fpm.sock
        path: /run/php/php{{ php_version }}-fpm.sock
