---
- name: Install dependency packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Add apt signing key
  ansible.builtin.get_url:
    url: "{{ php_apt_key_url }}"
    dest: "{{ php_apt_key_dest }}"
    mode: "0644"
- name: Add php repository
  ansible.builtin.apt_repository:
    filename: php
    repo: deb [signed-by={{ php_apt_key_dest }}] https://packages.sury.org/php/ {{ ansible_facts.distribution_release }} main
    state: present
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
