---
- name: Install dependency packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
## @see https://packages.sury.org/php/README.txt
- name: Install archive-keyring package
  ansible.builtin.apt:
    deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
- name: Add php repository
  ansible.builtin.apt_repository:
    filename: php
    repo: deb [signed-by={{ php_apt_key_dest }}] https://packages.sury.org/php/ {{ ansible_facts.distribution_release }} main
    state: present
