---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check composer command
      ansible.builtin.stat:
        path: /usr/local/bin/composer
      register: stat_result
    - name: Assert install composer command
      ansible.builtin.assert:
        that: stat_result.stat.exists
